config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about" 
  resources :articles
  get "signup", to: "users#new"
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: { minimum: 3, maximum: 80 }
    validates :description, presence: true, length: { minimum: 10, maximum: 140 }

end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles
    validates :username, presence: true, 
        uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true, 
        uniqueness: { case_sensitive: false }, 
        length: { maximum: 105 },
        format: { with: VALID_EMAIL_REGEX }

    has_secure_password    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
   
    def show
    end

    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def edit
    end

    def create
        @article = Article.new(article_params)
        @article.user = User.first
        if @article.save
            flash[:notice] = "Article was created successfully."
            redirect_to @article
          else
            render :new, status: :unprocessable_entity
        end
    end

    def update
        if @article.update(article_params)
            flash[:notice] = "Article was updated!"
            redirect_to @article
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @article.destroy
        redirect_to articles_path
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def about
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
        @articles = @user.articles
    end

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:notice] = "Hi #{@user.username}, Welcome to Blog Zone!"
            redirect_to articles_path
        else
            render "new", status: :unprocessable_entity
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "Your profile was updated successfully."
            redirect_to articles_path
        else
            render "edit"
        end
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<table class="table text-start m-4">
        <thead>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Author</th>
                <th colspan=3>Actions</th>
            </tr>
        </thead>
    <tbody>
    <% @articles.each do |article| %>
    <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= article.user.username.titleize %></td>
        <td><%= link_to "Show", article_path(article.id) %></td>
        <td><%= link_to "Edit", edit_article_path(article.id) %></td>
        <td><%= link_to "Delete", article_path(article.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>
    </tr>
    <% end %>
    </tbody>
</table>

app/views/articles/_form.html.erb
<div class="bd-example w-50 mx-auto">
<%= render "shared/errors", obj: @article %>
<%= form_with(model: @article, local: true, class: "text-start") do |f| %> 
    <div class="form-group mt-2"> 
        <%= f.label :title %> <br/>
        <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group mt-2"> 
        <%= f.label :description %> <br/>
        <%= f.text_area :description, class: "form-control", rows: 5 %>
    </div>

    <div class="col-lg-6 mx-auto mt-4">
        <%= f.submit class: "btn btn-primary btn-sm px-4 gap-4" %>
        <%= link_to "Index", articles_path, class: "btn btn-outline-secondary btn-sm px-4" %>
    </div>
<% end %>
</div>

app/views/articles/edit.html.erb
<h1 class="display-6 mb-4">Edit Article</h1>

<%= render "form" %>

app/views/articles/index.html.erb
<h1 class="display-6 mb-4">Articles Index</h1>



<%= render "article" %>

<div class="d-flex px-3 bd-highlight">
    <div class="p-2">
    <%= link_to "New Article", new_article_path, class: "btn btn-primary btn-sm px-4 gap-4"  %>
    <%= link_to "Home", root_path, class: "btn btn-outline-secondary btn-sm px-4" %>
    </div>
</div>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render "form" %>

 

app/views/articles/show.html.erb
<h1 class="display-6 mb-2"><%= @article.title %></h1>
<p class="text-muted">by <%= @article.user.username.titleize %></p>

<div class="highlight w-50 bg-light mx-auto mb-4 p-2 text-start" style="height: 300px">
<p><strong> Description: </strong> <%= @article.description %></p>
</div>
<div class="text-muted mb-4">
    <small>Created <%= time_ago_in_words(@article.created_at) %> ago</small>
    <% if @article.created_at != @article.updated_at %>
         <small>Edited <%= time_ago_in_words(@article.updated_at) %> ago</small> 
    <% end %>
</div>
<div class="col-lg-6 mx-auto">
    <%= link_to "Edit", edit_article_path(@article), class: "btn btn-primary btn-sm px-4 gap-4" %>
    <%= link_to "Delete", article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-sm px-4 btn-warning" %>
    <%= link_to "Index", articles_path, class: "btn btn-outline-secondary btn-sm px-4" %>
</div>    

app/views/layouts/_container.html.erb
<div class="px-4 py-5 m-5 text-center">
    <%= yield %>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <div class="alert alert-success text-start alert-dismissable fade show" role="alert">
        <div class="d-flex justify-content-between">
            <%= msg %>
           <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
       </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= render "layouts/container" do %>
        <%= render "layouts/messages" %>
        <%= yield %>
      <% end %>
  </body>
</html>

app/views/pages/about.html.erb
<h1 class="display-6 mb-4">This is the About Page</h1>

<div class="highlight w-50 bg-light mx-auto mb-4 p-2" style="height: 300px">
    <p>blog zone is everything to me.</p>
</div>
<div class="col-lg-6 mx-auto">
    <%= link_to "Index", articles_path, class: "btn btn-primary btn-sm px-4 gap-4" %> 
    <%= link_to "Home", root_path, class: "btn btn-outline-secondary btn-sm px-4" %>
</div>    

app/views/pages/home.html.erb
    <h1 class="display-4 mb-4">Welcome 2 Blog Zone</h1> 

    <div style="height: 300px" class="p-3 py-4 mb-2 text-center rounded w-50 mx-auto">
    ✧･ﾟ: *✧･ﾟ:* *:･ﾟ✧*:･ﾟ✧
    </div>
    <div class="col-lg-6 mx-auto">
        <%= link_to "Index", articles_path, class: "btn btn-primary btn-sm px-4 gap-4" %> 
        <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-sm px-4 gap-4" %>
        <%= link_to "About", about_path, class: "btn btn-outline-secondary btn-sm px-4" %>
    </div>

    

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger text-start alert-dismissable fade show" role="alert">
    <div class="d-flex justify-content-between">
      <h4 class="alert-heading h5">The <%= obj.class.name.downcase %> cannot be saved.</h4>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
        <li class="small"><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/_form.html.erb
<div class="bd-example w-50 mx-auto">
<%= render "shared/errors", obj: @user %>
<%= form_with(model: @user, local: true, class: "text-start form") do |f| %> 
    <div class="form-group mt-2"> 
        <%= f.label :username %> <br/>
        <%= f.text_field :username, class: "form-control", placeholder: "Enter your username" %>
    </div>

    <div class="form-group mt-2"> 
        <%= f.label :email %> <br/>
        <%= f.email_field :email, class: "form-control", placeholder: "Enter your email address" %>
    </div>

    <div class="form-group mt-2"> 
        <%= f.label :password %> <br/>
        <%= f.password_field :password, class: "form-control", placeholder: "Choose a password" %>
    </div>

    <div class="col-lg-6 mx-auto mt-4">
        <%= f.submit(@user.new_record? ? "Sign up" : "Update Profile", class: "btn btn-primary btn-sm px-4") %>
        <%= link_to "Index", articles_path, class: "btn btn-outline-secondary btn-sm px-4" %>
    </div>
<% end %>
</div>

app/views/users/_user.html.erb
<div class="d-flex flex-column">
    <% @users.each do |user| %>
    <div class="highlight w-50 bg-light mx-auto mb-4 p-2 text-center" style="height: 300px">
        <div class="text-center bg-secondary p-2">
            <h4 class="display-6 text-light"><%= user.username.titleize %></h4>
        </div>
        <div class="p-2">
            <img src="<%= user.img_url %>" alt="Picture" style="width: 100px;">
        </div>
        <div><%= user.articles.count %> articles</div>

        <div><%= link_to "Show", user_path(user.id) %></div>
        <div><%= link_to "Edit", edit_user_path(user.id) %></div>
    </div>
    <% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= render "form" %>

app/views/users/index.html.erb
<h1 class="display-6 mb-4">Users of Blog Zone</h1>

<%= render "user" %>

app/views/users/new.html.erb
<h1>Sign up for Blog Zone</h1>

<%= render "form" %>

app/views/users/show.html.erb
<h1><%= @user.username.titleize %>'s profile</h1>

<h3 class="text-center mt-4">Articles</h3>

<%= render "articles/article" %>